import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${site.name} — ${site.tagline}`,
    short_name: site.shortName,
    description: site.description,
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#f6f3ec",
    theme_color: "#f6f3ec",
    orientation: "portrait-primary",
    categories: ["education", "books", "productivity"],
    lang: "en-US",
    dir: "ltr",
    // Both entries are generated by app/icon.tsx and app/apple-icon.tsx, so
    // there are no icon files to keep in sync in /public. The 180px one is
    // marked maskable: its mark is inset far enough to survive platform
    // cropping, which the 32px favicon is not.
    icons: [
      { src: "/icon", sizes: "32x32", type: "image/png", purpose: "any" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "maskable" },
    ],
    shortcuts: [
      { name: "Search", short_name: "Search", url: "/search" },
      { name: "Study guides", short_name: "Guides", url: "/guides" },
    ],
  };
}
